conversation/promos-client

CHANGELOG.md, src/placementEngine.js, src/placementEngine.test.js
Fix an issue where the placementEngine was initially emitting all promos to subscribers, before filtering them.
=> [TC-916] Fix issue with placementEngine initial state

CHANGELOG.md, src/placementEngine.js, src/placementEngine.test.js, src/reducer.js, src/reducer.test.js
The context contains the list of _all_ candidate promos for the placement engine to filter. It also contains a reference to the window object.
=> Refactor the reducer to accept a context

CHANGELOG.md, package-lock.json, package.json, src/placePromos.test.js, src/placementEngine.js, src/placementEngine.test.js, src/reducer.js, src/reducer.test.js
When the promos engine receives a `click` event for a promo, it will add that promo to the list of engagements.
```json
{
"engagements":{
"promos":{
"2":{"count":10,"timestamp":"2019-04-26T04:08:38.093Z"},
"3":{"count":4,"timestamp":"2019-04-26T04:09:13.619Z"}
},
"groups":{
"2":{"count":14,"timestamp":"2019-04-26T04:09:13.619Z"}
},
"campaigns":{
"1":{"count":14,"timestamp":"2019-04-26T04:09:13.619Z"}
}
}
}
```
This means we can write constraints to ensure that the donation popups won't be shown if a user has already clicked on one of the donations promos
For example, if we want to ensure that a promo isn't shown if someone has already clicked one of the promos in the group:
```sql
groupId NOT IN user.engagements.groups
```
Or perhaps we don't want to show a promo if _any_ of the promos in …
=> [TC-915] Pass onClick function to placement engine subscribers

src/placementEngine.js, src/placementEngine.test.js, src/stateMachine.js, src/stateMachine.test.js
There was an issue with using a reducer function which caused the placement engine to emit the placed promos _every_ time an event was triggered. By using a state machine, we can have fine-grained control over when events are emitted.
How to Test
- Ensure that `promos-client` and TC are using the same node version
- Build the package: `make dist`
- In the promos client directory: `npm ln`
- In the TC directory: `npm ln @theconversation/promos-client`
- Fire up TC and check that promos work as expected. Note: because the promos are no longer reemitted for every event (i.e. when you dismiss a popup), reactively closing the popup no longer works. To fix this it will require a change in TC.
=> [TC-937] Fix issue with placement engine events

src/createContext.js, src/createContext.test.js, src/utils.js, src/utils.test.js
We want to add the ability for promos to appear when the user scrolls the page past a certain point. This PR doesn't get us all the way there, but it does lay some of the groundwork.
I added a `scroll` object to the context, which allows queries to be constrained based on the horizontal and vertical scroll offsets of the page:
```sql
scroll.percentY >= 0.75
```
Both of these values provided as a normalised percentage value (i.e. 0 <= n <= 1).
I toyed around with the idea of trying to use the [Intersection Observer API](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) to do this, but I think for the first cut a simple scroll percentage will work.
=> Include horizontal and vertical scroll percentages in the context

CHANGELOG.md, src/createContext.js, src/createContext.test.js, src/placementEngine.js, src/placementEngine.test.js
This PR adds a custom constraint parameter to the `placementEngine` function.
This will allow the calling application (TC) to provide a custom state object, which can be used in promo constraint queries:
```sql
custom.foo = 'bar'
```
This will be useful when we want to start writing constraints to match state in the TC application (e.g. donor status, etc.).
What do you think of the API? Should it be called something other than `custom`?
=> Add custom state to context

CHANGELOG.md, src/placePromos.js, src/placePromos.test.js, src/placementEngine.js, src/utils.js, src/utils.test.js
This PR has been extracted from my [reactive work](https://github.com/conversation/promos-client/pull/14).
I refactored the `placePromos` function to use a pseudorandom number generator (PRNG) when picking promos at random.
Being able to seed the PRNG is important, as it allows us to deterministically pick the same promos for the same seed value.
This is functionally equivalent to what we already have, so there is no change as far as TC is concerned.
=> Use a PRNG when picking promos

package-lock.json
There was a [security issue](https://github.com/conversation/promos-client/network/alert/package-lock.json/set-value/closed) with earlier versions.
=> Upgrade set-value to 2.0.1

src/placementEngine.js, src/userState.js, src/userState.test.js
Some browsers might have their `localStorage` feature disabled, due to privacy and tracking reasons. We still want to render promos, even if that means serving less targeted promos.
**Manual testing steps**
- At the `master` branch
- Run `make node_modules dist`
- Run `npm link`
- Link it in a project running the `promos-client` (e.g.: `tc`)
- Run `npm link @theconversation/promos-client` in the project folder
- Keep in mind: you should disable `tc`'s Webpack Docker service and use the host `npm run webpack:dev` to be able to test this branch
- Tip: remember to configure `WEBPACK_INLINE_DEV_SERVER: http://docker-host:8080/` for `tc`
- Disable cookies/local storage for your `localhost:3000`
- Chrome: visit `chrome://settings/content/cookies` and add `localhost:3000` to the block list
- …
=> Use default user state when local storage isn't present

src/utils.js, src/utils.test.js
Currently on iOS, "overscrolling" the edge of the screen results in values of `Infinity` or `NaN` due to dividing by zero or zero being divided by some other value.
By clamping the values between 0 and 1 we avoid this problem.
=> Ensure horizontal and vertical scroll values are clamped between 0 and 1

CHANGELOG.md, src/index.js
This allow importing the parser, allowing evaluating constraint expressions outside the placement engine.
=> Expose the CQL parser

Makefile, package.json
This PR updates the package config to include ESM files, as well as the common JS files built by Babel.
We can include both types of packages using [package exports](https://webpack.js.org/guides/package-exports/) in the `package.json` file. This allows us to perform tree shaking properly, as TC will include the ESM version of the package, while still allowing the package to be required from a common JS file.
More info: https://www.sensedeep.com/blog/posts/2021/how-to-create-single-source-npm-module.html
If you want to test this works locally:
* Build the promos-client package `make dist`
* Make the package linkable `npm ln`
* Link to the package in TC: `npm ln @theconversation/promos-client`
* Build the bundle: `npm run webpack:prod`
=> Target ES modules

package-lock.json, package.json, src/placementEngine.js, src/placementEngine.test.js, src/stateMachine.js, src/stateMachine.test.js
This PR replaces the Bulb.js reactive library with RxJS.
This was mainly for two reasons:
1. RxJS is an actively maintained reactive programming library (Bulb.js was written by me) and has much better [documentation](https://rxjs.dev/api), etc.
2. The modularity of RxJS should allow for a smaller bundle size.
Things work in much the same way as with Bulb.js, mostly it is just a change in nomenclature:
* RxJS calls streams an "Observable" (Bulb.js calls them a "Signal").
* RxJS calls multicast streams a "Subject" (Bulb.js calls them a "Bus").
* RxJS has no state machine operator, so we have to use `scan` instead. This scans a function over an observable, emitting the intermediate values as they are transformed.
Also, the way you join operators into a pipeline is different with RxJS. You …
=> Replace Bulb with RxJS

CHANGELOG.md, Makefile, babel.config.js, package.json
Mostly just bringing it into line with our other packages which compile and work fine with Webpack 5, the only notable addition is:
```js
"browser": {
"fs": false,
"path": false
},
```
I didn't really have the time to investigate this part properly, but on the surface it looks like the autogenerated `src/parser.js` code is just inappropriate for browsers, with that extra config it'll basically just tell webpack to ignore `require` statements for `fs` and `path`, which probably shouldn't be there in the first place. But it at least works.
Will release a new version separately, probably a major version bump because it changes the distributables a fair bit.
=> Fix esm build for use with Webpack 5

.github/dependabot.yml
We don't want dependabot opening update pull requests that aren't related to security advisories.
=> Configure dependabot to only open PRs for production security advisories

.github/workflows/package.yml, Makefile, package.json
We were missing files in the 6.0.0 release and didn't notice, because the `package` workflow wasn't actually working.
Fixed now, you can see that the 6.0.1-rc3 release contains files:
https://github.com/conversation/promos-client/runs/5178452834
```
./promos-client$ cat package.json | grep version
"version": "6.0.1-rc3",
./promos-client$ tree dist | wc -l
45
```
=> Fix package publish GitHub workflow

src/index.js, src/index.test.js
In TC, we're [looking at bringing donations state into promos](https://github.com/conversation/tc/pull/12488), which will mean manipulating the user state in local storage. That will mean that TC will need the ability to initialise the user state, and we'd [like to be able to](https://github.com/conversation/tc/pull/12488#discussion_r872348778) bring this in from promos-client. Export it here (and add some quick specs on our exports for good measure).
=> Export DEFAULT_USER_STATE

CHANGELOG.md, package-lock.json, package.json, types.d.ts
We are not declaring any types for the `promos-client` at the moment, but declaring an empty module will avoid TypeScript compilation error code 7016, which assumes we are implicitly declaring that exports have the "any" type.
We are now explicitly declaring it has the "any" type.
* At the `main` branch
* Link this project to a project that is using the `@theconversation/promos-client` and TypeScript
* Example:
```js
// At `tc/frontend/package.json` dependencies, you can reference the relative/absolute path to your files
{
"dependencies": {
"@theconversation/promos-client": "file:../../promos-client",
}
}
```
_You could also use `npm link`, whatever technique you prefer._
* Create the `promos-client` distribution version (e.g.: `make dist`)
* Import the placements engine and try to …
=> Declare TS module to infer the `any` type to promos client exports

src/stateMachine.js, src/stateMachine.test.js
We now add user donation details in the user state (https://github.com/conversation/tc/pull/12488). However, the promos state machine is not notified of this asynchronous change to the user state, and so will stomp those changes if there is a subsequent update. Add an event handler which will allow TC to notify the promos client of any changes.
=> Handle external changes to user

CHANGELOG.md, package.json
* Related to https://github.com/conversation/promos-client/pull/45
While https://github.com/conversation/promos-client/pull/45 created the `types.d.ts` file, the pull request didn't include it in the `package.json`.
This PR fixes this, making the file available after module is downloaded from `npm`.
=> Include `types.d.ts` file when publishing to npm

package-lock.json
GitHub actions CI s using node 16.17.0, which failed when running the `npm ci` command.Updating the `acorn` dev dependency should resolve the issue.
`acorn` is a dev/test dependency only (jest and standard).
=> Update dev dependencies using node 16.17.0

src/placePromos.js, src/placePromos.test.js
* Related to consent management work: https://trello.com/c/ONAKCyni/9818-consent-management
This PR adds a new promo property to the promos engine context: the `type`.
When placing promos, the engine will now copy the `promo.type` property to its context, allowing us to write CQL queries with it, such as:
```
window.location.search =~ "promos=on" AND type NOT IN ["DonationDialog", "DesktopBanner"]
```
Such query allows us to only show promos when we have the `?promos=on` query string, and campaign or promo will never allow promo types of the `DonationDialog` and `DesktopBanner`!
This gives us the ability to hide certain creative types at will, meaning that we can hide certain promos if users didn't give consent.
=> Pass promo types to the promos engine context

src/placementEngine.js, src/placementEngine.test.js, src/stateMachine.js, src/stateMachine.test.js
When invoking the promos engine refresh event, we want to be able to update its custom context object, allowing us to update the custom context of the placement engine after it has been initialized.
This gives us the ability to update the placement engine context after it has been initialized.
E.g.:
```
const signal = placementEngine(storage, promos, context)
// We are now going going to add more information to the placement
// engine context:
const consent = true
signal.next({ type: "refresh", custom: { ...context, consent } })
```
=> Allow the placement engine refresh event to pass a custom context

src/placePromos.js, src/placePromos.test.js
Implement the logic from https://github.com/conversation/tc/pull/16834 here.
We ran into an issue where two promos in the same slot where being triggered at the same time.  This is an attempt to prevent this.
=> Limit one promo per slot
